### ISSUE TITLE
Add configuration option to set the sitemap name to use [openHAB]

### ISSUE THREAD

**Issue by sumnerboy12** [schdef/homecompanion#10]

**Comment by sumnerboy12** [comment]
Also, just had a quick look in your code and noticed this;

```    
    @Override
    public List getDevices() throws ServiceNotAvailable {
        return getDevices("http://" + HOST + ":" + PORT + "/rest/sitemaps/demo?type=json");
    }```

Shouldn't this be using the http/https config option?

**Comment by schdef** [comment]
Sure thing. HTTP is the default behaviour, but in the preferences there is apossibility to activate HTTPS, which is handled in the AbstractConfig - https://github.com/schdef/homecompanion/blob/master/mobile-common/src/main/java/de/stefanheintz/smarthome/config/AbstractConfig.java#L214

**Comment by sumnerboy12** [comment]
Ah great - sorry missed that! Will you be able to add the sitemap name config? Looking forward to giving this a go with my watch!

**Comment by schdef** [comment]
How do you think should it look like? Any suggestions?

**Comment by sumnerboy12** [comment]
just a simple text field in the openHAB configuration UI to allow the user to enter the sitemap name - since most people who use openHAB in a *production* environment* will not have a sitemap named *demo*.

**Comment by schdef** [comment]
Added additional field for openHAB to enter sitemap name.

**Comment by sumnerboy12** [comment]
Many thanks!
