### ISSUE TITLE
Openhab not showing items

### ISSUE THREAD

**Issue by Woutch** [schdef/homecompanion#11]
Dear,

I installed your app and registered it with my openhab server at home. I have created an "mobile" version off my dashboard thanks to the ability to select one. But the list stays empty, no error show.

Bellow you can find the returned json. This is with selfsigned https and external username/password. But that should be ok, else I would receive an error.

I get 1 error when the list only contains one item. Something about cannot convert to json array. This disapears when I add a second one, but it is still empty.

PS: changed the dns names :-)

{
name: "mobile",
label: "Mobile",
link: "https://xxx.com:5443/rest/sitemaps/mobile",
homepage: {
id: "mobile",
title: "Mobile",
link: "https://xxx.com:5443/rest/sitemaps/mobile/mobile",
leaf: "false",
widget: [
{
widgetId: "mobile_0",
type: "Switch",
label: "Gang beneden",
icon: "switch-on",
item: {
type: "SwitchItem",
name: "gang_beneden",
state: "ON",
link: "https://xxx.com:5443/rest/items/gang_beneden"
}
},
{
widgetId: "mobile_1",
type: "Switch",
label: "Tuinverlichting Vooraan",
icon: "socket-on",
item: {
type: "SwitchItem",
name: "Relay_8",
state: "ON",
link: "https://xxx.com:5443/rest/items/Relay_8"
}
}
]
}
}

**Comment by schdef** [comment]
I'd like to right a test for it. Can you add the sitemap configuration in json format as well?

**Comment by Woutch** [comment]
Here is the sitemap json:

{
sitemap: [
{
name: "default",
label: "Thuis",
link: "https://xxx.com:5443/rest/sitemaps/default",
homepage: {
link: "https://xxx.com:5443/rest/sitemaps/default/default",
leaf: "false"
}
},
{
name: "mobile",
label: "Mobile",
link: "https://xxx.com:5443/rest/sitemaps/mobile",
homepage: {
link: "https://xxx.com:5443/rest/sitemaps/mobile/mobile",
leaf: "false"
}
}
]
}

**Comment by schdef** [comment]
I verified the error and added an automated test with some improvements.

**Comment by schdef** [comment]
Please test the current test version 1.8.7. It should show now the items.

**Comment by Woutch** [comment]
YES! I can confirm my switches are loading now in android and on my watch. 
So cool to open the garage door with my watch :+1:
